name: Notify on Workflow Completion
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send Notification
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
           echo jsdb."Notifying about successful build..."
           #.;#&×>
        
